export default {
  api: {
    "type": "video",
    "version": "1.0",
    "provider_name": "Vimeo",
    "provider_url": "https://vimeo.com/",
    "title": "DEDUCKED",
    "author_name": "Nolan Downs",
    "author_url": "https://vimeo.com/nolanjdowns",
    "is_plus": "0",
    "account_type": "pro",
    "html": "<iframe src=\"https://player.vimeo.com/video/271787074?app_id=122963\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"DEDUCKED\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>",
    "width": 640,
    "height": 360,
    "duration": 150,
    "description": "Round and round go the circles of life.\n\nSpecial thanks to Pepper the dog for inspiration.\n\nAnimation by Nolan J. Downs\nhttp://nolanjdowns.com/\n\nSound Design by Chris Kalis and Harry Brenner\nhttp://christopherkalis.com/\n\nMore sounds by Chris and Harry\nhttp://thechandeliers.com/",
    "thumbnail_url": "https://i.vimeocdn.com/video/703291331_640.webp",
    "thumbnail_width": 640,
    "thumbnail_height": 360,
    "thumbnail_url_with_play_button": "https://i.vimeocdn.com/filter/overlay?src0=https%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F703291331_640.webp&src1=http%3A%2F%2Ff.vimeocdn.com%2Fp%2Fimages%2Fcrawler_play.png",
    "upload_date": "2018-05-24 21:30:04",
    "video_id": 271787074,
    "uri": "/videos/271787074"
  },
  result: {
    title: "DEDUCKED",
    addedDate: "2018-05-24 21:30:04",
    authorName: "Nolan Downs",
    width: 640,
    height: 360,
    duration: 150,
    thumbnail: "https://i.vimeocdn.com/video/703291331_640.webp",
    thumbnailWidth: 640,
    thumbnailHeight: 360,
    caption: "DEDUCKED",
    src: "https://i.vimeocdn.com/video/703291331_640.webp",
  }
};
